# Generated by Django 2.2.10 on 2020-03-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_clientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
