# Generated by Django 2.2.10 on 2020-03-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200303_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
