# Generated by Django 2.2.10 on 2020-03-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200325_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
