# Generated by Django 2.2.10 on 2020-03-25 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20200325_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', 'unclaimed'), ('S', 'scheduled'), ('F', 'finished'), ('C', 'canceled'), ('I', 'incompete')], default='U', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.ClientProfile')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='accounts.ContractorProfile')),
            ],
        ),
    ]
